use_frameworks! :linkage => :static

platform :ios, '10.0'

target 'YCIMModule_Example' do
  pod 'YCIMModule', :path => '../'
  
  pod 'Masonry', '~> 1.1.0'
  
#  pod 'TUISearch', '~> 6.8.3374'
  target 'YCIMModule_Tests' do
    inherit! :search_paths

    
  end
end
